title: Bean Validation
# interpolate content of the markup like #{page.title}
interpolate: true

asciidoctor:
  :safe: safe
  :attributes:
    experimental: true
    imagesdir: .@
    icons: font
    idprefix: ''
    idseparator: '-'
    sectanchors: ''
    linkattrs: ''
    source-highlighter: coderay
    coderay-css: style


profiles:
  development:
    disqus_developer: true
  staging:
    disqus_developer: true
    base_url: http://staging.beanvalidation.org/
  production:
    base_url: http://beanvalidation.org/

google_analytics:
  account: UA-24703879-1
disqus: beanvalidation
